### ISSUE TITLE
Horde_Translation class undefined

### ISSUE THREAD

**Issue by jaredhughes** [bluestatedigital/bsd-api-php#1]
lib/Horde/Exception/Translation.php, Line 17:

`class Horde_Exception_Translation extends Horde_Translation`

Horde_Translation is undefined, causing autoload to fail.

**Comment by tomkel5** [comment]
Hey @jaredhughes,

Do you still run into this problem? I've reworked the library to use Guzzle instead of Horde. Try out v2.0 — that'll probably work for you. Slightly different objects/method calls, but I think you'll find it easier to use.
