### ISSUE TITLE
Any docs here?

### ISSUE THREAD

**Issue by jahrichie** [bluestatedigital/bsd-api-php#3]
Is there any documentation or examples for this wrapper?

**Comment by tomkel5** [comment]
Hi Richard,

Sorry it's taken a while for us to see this... We've just made some changes to the library. It's now PSR-4 compliant, and uses Guzzle on the back end to manage HTTP connections. There's a simple example in the readme, and a test class called `ExampleTest`, where you can try it out with your own credentials.

Documentation about what API calls are available can be found here:

https://tools.bluestatedigital.com/pages/our-api#xml-api-ref

Hope that helps! :smile:
